# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release-branch:
        description: branch of the deploy
        default: 'master'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node_version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Echo input
        run: |
          echo $release_branch
        env:
          release_branch: ${{ github.event.inputs.release-branch }}
      
      # gerar o relatório em html
      - run: npm run report:cucumber
      
      # publicar relatorio em uma github pages do projeto
      - name: Deploy do GithubPages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: cypress/reports
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
